imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator: { fallback: %locale% }
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: "%locale%"
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:fields.html.twig'
